[phases.setup]
nixpkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install", "pnpm add medusajs-launch-utils@latest -g"]

[phases.build]
cmds = ["pnpm build", "mkdir -p .medusa/server", "cp medusa-config.js .medusa/server/"]

[start]
cmd = "pnpm start" 