[build]
builder = "NIXPACKS"
buildCommand = "bun install"

[deploy]
numReplicas = 1
startCommand = "bun start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Replace this with your actual project ID from Railway dashboard
[project]
# Get this from Railway dashboard > Project > Settings > Project ID
id = "a7713257-24ad-40dd-8bc1-015aa8733b04" 