name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
      - 'railway-deploy.trigger'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Check Railway CLI Version
        run: railway --version
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Global Dependencies
        run: bun add medusajs-launch-utils@latest -g

      - name: Verify Token and Project ID
        run: |
          echo "Token length: ${#RAILWAY_TOKEN}"
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "RAILWAY_TOKEN is empty"
            exit 1
          else
            echo "RAILWAY_TOKEN is set (masked for security)"
          fi
          
          echo "Project ID: $RAILWAY_PROJECT_ID"
          if [ -z "$RAILWAY_PROJECT_ID" ]; then
            echo "RAILWAY_PROJECT_ID is empty"
            exit 1
          else
            echo "RAILWAY_PROJECT_ID is set"
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: "a7713257-24ad-40dd-8bc1-015aa8733b04"
          
      - name: Check Project Status
        run: railway status --json
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: "a7713257-24ad-40dd-8bc1-015aa8733b04"
          
      - name: List Available Services
        run: |
          echo "Attempting to list all services in project..."
          # Using a trick to output service list without interactive prompt
          echo '{"projectId":"$RAILWAY_PROJECT_ID"}' > railway.json
          railway service --json || echo "Service listing failed but continuing..."
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: "a7713257-24ad-40dd-8bc1-015aa8733b04"
          
      - name: Check Backend Service Variables
        run: railway variables -s Backend --json || echo "Variable listing failed but continuing..."
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: "a7713257-24ad-40dd-8bc1-015aa8733b04"

      # Deploy the backend directly with path specified as positional argument
      - name: Deploy Backend
        run: |
          # Deploy from the backend directory explicitly
          cd backend && railway up . -d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: "a7713257-24ad-40dd-8bc1-015aa8733b04"
          CI: true 