name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
      - 'railway-deploy.trigger'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Railway CLI
        run: npm install -g @railway/cli
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Global Dependencies
        run: bun add medusajs-launch-utils@latest -g

      - name: Create Clean Deployment Directory
        run: |
          # Create a clean directory for deployment
          mkdir -p /tmp/backend-deploy
          
          # Copy all backend files to the deployment directory
          cp -r backend/* backend/.env* /tmp/backend-deploy/
          
          echo "Contents of deployment directory:"
          ls -la /tmp/backend-deploy/

      - name: Deploy to Railway
        run: |
          # Set current directory to the clean deployment directory
          cd /tmp/backend-deploy
          
          # Set up a minimal Railway config file to ensure it deploys to the correct service
          echo '{
            "$schema": "https://railway.app/railway.schema.json",
            "build": {
              "builder": "NIXPACKS",
              "buildCommand": "bun install"
            },
            "deploy": {
              "numReplicas": 1,
              "startCommand": "bun start",
              "restartPolicyType": "ON_FAILURE",
              "restartPolicyMaxRetries": 10
            }
          }' > railway.json
          
          # Deploy with detached mode
          railway up -d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: "a7713257-24ad-40dd-8bc1-015aa8733b04"
          RAILWAY_SERVICE: "Backend"
          CI: true 