name: Deploy Storefront

on:
  push:
    branches:
      - master
    paths:
      - 'storefront/**'
      - '.github/workflows/storefront-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service storefront
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 